services:
  backend:
    build:
      context: ./vidyadham_backend
    container_name: vidyadham_backend
    env_file:
      - ./vidyadham_backend/.env
    ports:
      - "5003:5003"
    restart: unless-stopped

  frontend:
    build:
      context: ./vidyadham_frontend
    container_name: vidyadham_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: unless-stopped
